---
title: "La Comédie humaine"
description: |
  Follow here my current reading project on reading all the books from The Human Comedy, from Honoré Balzac
---


![Source:
[Wikimedia Commons, public domain image](https://commons.wikimedia.org/wiki/File:Balzac_-_La_Com%C3%A9die_humaine_-_%C3%89ditions_Furne.jpg?uselang=fr)](balzac_image.jpg){width=70}


<style>
body {
text-align: justify}
</style>

The Human Comedy is a vast series of some 90 novels and novellas by [**Honoré de Balzac**](https://pantheon.world/profile/person/Honor%C3%A9_de_Balzac), known in the original French as La Comédie Humaine. The books that made up the series were published between 1829 and 1847. There are many orders to read them and a debate among scholars on what order should the books be read. I am following the one suggested by this [**reading group here**](https://balzacbooks.wordpress.com/suggested-reading-order-of-the-human-comedy/) that used most of the recommendations from William Hobart Royce's book [**Balzac as He Should Be Read**](http://onlinebooks.library.upenn.edu/webbin/book/lookupid?key=ha001203670). I chose this one after a long search due to the fact that the group was more enthusiastic and not so much literary critics. I wanted to have a deeper feeling for French society and institutions in, but, most importantly, I wanted to partake in a long, long, long, reading project. I adore long books, and tend to hold on to stories that unravell slowly and painfully (I know - tough to understand why anyone would like such a thing). Everytime I finish one of these books, however, I feel a tremendous empty feeling (junky vibes anyone?) and was seeking an experience that would allow for a more prolonged feeling of being inside a story and avoid the blues. If you share the same feeling as I do or are just interested in my analysis of each story just stay tuned for more updates on this.  
