---
title: "Formal Demography"
description: |
  Follow here my ideas and projects connected to Formal Demography
---

![Source: 
[Elaborated by Monica Alexander](https://formaldemography.github.io/working_group/)](formal.png){width=30}


<style>
body {
text-align: justify}
</style>


Here are some projects connected to my interest in Formal Demography. I have recently co-organized a working group on Formal Demography together with [Monica Alexander (University of Toronto)](https://www.monicaalexander.com/) and [Ryohei Mogi (University of Oxford)](https://www.ox.ac.uk/news-and-events/find-an-expert/dr-ryohei-mogi). The Formal Demography Working Group aims to bring together formal demography scholars and those interested in formal demography to discuss recent and classic work, brainstorm new ideas, and to foster new collaborations. If you are interested, follow our group website and subscribe to the mail list [**here**](https://formaldemography.github.io/working_group/) and check out our [**github**](https://github.com/formaldemography/working_group).

Our goal with the group is to bring an international community of scholars together with formal demography as the focus on creating a supportive and inclusive environment to learn and encourage people to work with formal methods. We also discuss the past, present and future of formal demography.

Within formal demography, I am particularly interested in stable population theory, redistribution of deaths and exploring lifetable relationships. I am also interested in Tempo effects in mortality and the sensitvity of life expectancy as an indicator, as recently addressed in [**this**](https://www.karger.com/Article/FullText/500955) publication. Stay tuned for further developments! A bunch of stuff can be found in my [**github account**](https://github.com/vdilego) as well.
