---
title: "Publications"
description: |
  My list of publications
---

# Published

[**di Lego, V.**, Sanchez-Romero, M., & Fürnkranz-Prskawetz, A. (2022). The impact of COVID-19 vaccines on the Case Fatality Rate: The importance of monitoring breakthrough infections. International Journal of Infectious Diseases 10.1016/j.ijid.2022.03.059](https://www.sciencedirect.com/science/article/pii/S1201971222001977?via%3Dihub)

[Luy, M., Sauerberg, M., Muszyńska-Spielauer, M. and **di Lego, V.** (2021). Decrease in Life Expectancy in Germany in 2020: Men from Eastern Germany Most Affected. Comparative Population Studies. 46, (Dec. 2021). DOI:https://doi.org/10.12765/CPoS-2021-20](https://comparativepopulationstudies.de/index.php/CPoS/article/view/460)

[**di Lego, V.** (2021) Health expectancy indicators: what do they measure?. Cad Saúde Colet, 2021;29 (esp.): 115-129. https://doi.org/10.1590/1414-462X202199010376](https://www.scielo.br/j/cadsc/a/wc8DBFJs4jRfdR4DG4KT6YM/) 

[Nepomuceno M. R., **di Lego, V.**, Turra, C.M. (2021). Gender disparities in health at older ages and their consequences for well-being in Latin America and the Caribbean. Vienna Yearbook of Population Research 2021 (Vol. 19). doi:10.1553/populationyearbook2021.res2.1](https://www.austriaca.at/0xc1aa5576_0x003c8cc2.pdf)

[Sánchez-Romero M, **di Lego V.**, Prskawetz A, L. Queiroz B (2021) An indirect method to monitor the fraction of people ever infected with COVID-19: An application to the United States. PLoS ONE 16(1): e0245845.](https://doi.org/10.1371/journal.pone.0245845)

[Spitzer, S., **di Lego, V.**, Greulich, A. and Muttarak, R. (2021). A demographic perspective on human wellbeing: Concepts, measurement and population heterogeneity. Vienna Yearbook of Population Research, 19.](https://doi.org/10.1553/populationyearbook2021.int01)

[**di Lego, V.**; Di Giulio, P.; Luy, M.(2020). "Gender differences in healthy and unhealthy life years", in: Jagger, C.; Crimmins, E.; Saito, Y.; De Carvalho Yokota, R.; Van Oyen H.; Robine, J.-M. (eds.): International Handbook of Health Expectancies, Cham, Springer: 151-172](https://link.springer.com/chapter/10.1007%2F978-3-030-37668-0_11)


[Sánchez-Romero, M.; **di Lego, V.**; Fürnkranz-Prskawetz, A.; Queiroz, B. L. (2020). How many lives can be saved? A global view on the impact of testing, herd immunity and demographics on COVID-19 fatality rates, ECON WPS, No. 05/2020, Vienna University of Technology, Institute of Statistics and Mathematical Methods in Economics, Research Group Economics, Vienna](https://www.econstor.eu/bitstream/10419/218732/1/1698672055.pdf)

[Sobotka, Tomas; Zeman, Krystof; Spitzer, Sonja; Reiter, Claudia; **di Lego, Vanessa**; Yildiz, Dilek; Özdemir, Caner; Goujon, Anne; Binder-Hammer, Bernhard; Bloom, David E. ; Fan, Victoria Y. ;  Kufenko,Vadim;  Ogbuoji, Osondu; Prettner, Klaus ;  Yamey, Gavin;  Rowe, Francisco;  Bell, Martin; Bernard, Aude ; Charles-Edwards,Elin; Scherbov, Sergei. 2020: European Demographic Datasheet , Vienna Institute of Demography: http://www.populationeurope.org/](https://www.oeaw.ac.at/vid/data/demographic-data-sheets/european-demographic-data-sheet-2020)

[Sobotka T., Brzozowska Z., Muttarak R., Zeman K. & **di Lego, V**. (2020). Age, gender and COVID-19 infections(p. 16). https://doi.org/10.1101/2020.05.24.20111765](https://www.medrxiv.org/content/10.1101/2020.05.24.20111765v1)

[**Di Lego, Vanessa**; Di Giulio, Paola; Luy, Marc.(2020). "Gender differences in healthy and unhealthy life years", in: Jagger, C.; Crimmins, E.; Saito, Y.; De Carvalho Yokota, R.; Van Oyen H.; Robine, J.-M. (eds.): International Handbook of Health Expectancies, Cham, Springer: 151-172](https://link.springer.com/chapter/10.1007%2F978-3-030-37668-0_11)


[Sánchez-Romero, Miguel; **Di Lego, Vanessa**; Fürnkranz-Prskawetz, Alexia; Queiroz, Bernardo Lanza (2020). How many lives can be saved? A global view on the impact of testing, herd immunity and demographics on COVID-19 fatality rates, ECON WPS, No. 05/2020, Vienna University of Technology, Institute of Statistics and Mathematical Methods in Economics, Research Group Economics, Vienna](https://www.econstor.eu/bitstream/10419/218732/1/1698672055.pdf)

[Sobotka, Tomas; Zeman, Krystof; Spitzer, Sonja; Reiter, Claudia; **di Lego, Vanessa**; Yildiz, Dilek; Özdemir, Caner; Goujon, Anne; Binder-Hammer, Bernhard; Bloom, David E. ; Fan, Victoria Y. ;  Kufenko,Vadim;  Ogbuoji, Osondu; Prettner, Klaus ;  Yamey, Gavin;  Rowe, Francisco;  Bell, Martin; Bernard, Aude ; Charles-Edwards,Elin; Scherbov, Sergei. (2020) European Demographic Datasheet , Vienna Institute of Demography: http://www.populationeurope.org/](https://www.oeaw.ac.at/vid/data/demographic-data-sheets/european-demographic-data-sheet-2020)

[Sobotka T., Brzozowska Z., Muttarak R., Zeman K. & **di Lego, Vanessa**. (2020). Age, gender and COVID-19 infections(p. 16). https://doi.org/10.1101/2020.05.24.20111765](https://www.medrxiv.org/content/10.1101/2020.05.24.20111765v1)

[**di Lego, Vanessa**; Lazarevič, Patrick; Luy, Marc: “The Male-Female Health-Mortality Paradox”, in: Gu, Danan; Dupre, Matthew E. (eds.): Encyclopedia of Gerontology and Population Aging, Dordrecht et al., Springer, doi: 10.1007/978-3-319-69892-2_798-2 (published online: 17.10.2019)](https://link.springer.com/referenceworkentry/10.1007%2F978-3-319-69892-2_798-2)

[Luy, Marc; Di Giulio, Paola; **di Lego, Vanessa**; Lazarevič, Patrick; Sauerberg, Markus, (2019). "Life expectancy: frequently used, but hardly understood", Gerontology 66(1): 95-104 (published online: 08.08.2019)](https://pubmed.ncbi.nlm.nih.gov/31390630/)

[Sobotka, Tomas; Zeman, Krystof; **di Lego, Vanessa**; Goujon, Anne; Hammer, Bernhard; Loichinger, Elke; Sauerberg, Markus; Luy, Marc; Rengs, Bernhard, (2018) European Demographic Datasheet , Vienna Institute of Demography: http://www.populationeurope.org/](https://www.oeaw.ac.at/vid/data/demographic-data-sheets/european-demographic-data-sheet-2018)

[**di Lego V.**, Turra C., Cesar C. (2017). Mortality selection among adults in Brazil: The survival advantage of Air Force officers. Demographic Research (37) 41:1339–1350. doi:10.4054/DemRes.2017.37.41](https://www.demographic-research.org/volumes/vol37/41/default.htm)

# Work in progress

**di Lego, V**. Who has been saved more? Trends in the gender gap in mortality through the revivorship approach. Demographic Research. Revise and Resubmit

Spitzer, Sonja; **di Lego, Vanessa**; Kuhn, Michael; Roth, Christian; Berger, D. Socio-economic environment and survival in patients after ST-segment elevation myocardial infarction (STEMI): An observational study for the City of Vienna. BMJ Open. Resubmitted after first Review

**di Lego, V.**; Sauerberg, M. (2022) The Sensitivity of the Healthy Life Years Indicator: Approaches for Dealing with Age-Specific Prevalence Data. CPoS. Comparative Population Sutdies. Under Review

Aburto, J. M; **di Lego, V**; Riffe, T; Kashyap, R; Torrisi, O; van Raalte, A.  Global contribution of violence to lifetime uncertainty.

**di Lego, V.**, Spitzer, S. Lazarevic, P. Representation and measurement errors in health surveys and their impact on health expectancies.

Remund, A.: **di Lego, V.**  How many lives do we live? Unifying lifesaving approaches

Goldstein, J.; **di Lego, V.** Will mortality fall after the pandemic? A formal analysis of selection effects after a shock.

**di Lego, V.**; Nepomuceno, M; Turra, C. Gender Inequality in Healthy Ageing: A Cross-National Comparison
